// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwugjsIeuvxlvFYS_BLYrxZf3RmlYjx-c',
    appId: '1:239265152832:web:6d534bcedb9d91eb2384a5',
    messagingSenderId: '239265152832',
    projectId: 'modul3-3d5be',
    authDomain: 'modul3-3d5be.firebaseapp.com',
    storageBucket: 'modul3-3d5be.appspot.com',
    measurementId: 'G-V2KMZECVHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4O0eXAFsbNNLRhVeGPGte4aF6su6y48',
    appId: '1:239265152832:android:aa09baa082c432702384a5',
    messagingSenderId: '239265152832',
    projectId: 'modul3-3d5be',
    storageBucket: 'modul3-3d5be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03LFIcruj1kPl_L2W3gQFXmm77EogDL4',
    appId: '1:239265152832:ios:a61f031851ce91f52384a5',
    messagingSenderId: '239265152832',
    projectId: 'modul3-3d5be',
    storageBucket: 'modul3-3d5be.appspot.com',
    iosBundleId: 'com.example.codelabModul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA03LFIcruj1kPl_L2W3gQFXmm77EogDL4',
    appId: '1:239265152832:ios:a61f031851ce91f52384a5',
    messagingSenderId: '239265152832',
    projectId: 'modul3-3d5be',
    storageBucket: 'modul3-3d5be.appspot.com',
    iosBundleId: 'com.example.codelabModul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwugjsIeuvxlvFYS_BLYrxZf3RmlYjx-c',
    appId: '1:239265152832:web:2fac7716776299b02384a5',
    messagingSenderId: '239265152832',
    projectId: 'modul3-3d5be',
    authDomain: 'modul3-3d5be.firebaseapp.com',
    storageBucket: 'modul3-3d5be.appspot.com',
    measurementId: 'G-LW1S1YYYEP',
  );
}
